"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


#un in us


APP = ['runMain.py']
DATA_FILES = ['EmotionRecongnition.py',
              'image1_rc.py',
              'load_and_process.py',
              'Pic2py.py',
              'real_time_video_me.py',
              'slice_png.py',
              'train_emotion_classifier.py',
              'cnn.py'
              ]
OPTIONS = {'includes':
               ['PyQt5',
                'numpy',
                'cv2',
                'pandas',
                'imutils',
                'keras.models',
                'keras.preprocessing.image',
                'keras.callbacks',
                'sklearn.model_selection',
                'keras.layers',
                'keras.regularizers'
                ]
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
